Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/',include('blog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/',include('blog.api_urls')),
    path('email/',include('send.urls'))


   # path('/<int:>/',include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root =settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

Blog/blog/urls.py
from django.urls import path 
from blog import views

app_name ='blog'
urlpatterns =[
    path('', views.homeview.as_view(),name ='home'),
    path('<int:pk>/', views.detailview.as_view(),name ='any_name'),
    path('blogs/add/',views.blogcreate.as_view(),name ='blog_add'),
    path('blogs1/add/',views.blog1create.as_view(),name ='blog_content_add'),
    #update_blog
    path('blogs/<int:pk>/',views.blogupdate.as_view(),name ='blog_update'),
    #delete
    path('blogs/<int:pk>/delete/',views.blogdelete.as_view(),name ='blog_delete'), 

    #registration
    path('register/',views.UserFormview.as_view(),name ='register'),
    #search
    path('search/',views.SearchResultView.as_view(),name ='search'),
    path('blogsview/', views.BlogsView.as_view(),name ='blogsview'),
    path('blogsview/<int:pk>/', views.Blogs1View.as_view(),name ='blogsview'),
     

    
]

Blog/send/urls.py
from django.urls import path 
from send import views

app_name ='send'
urlpatterns =[

    path('1', views.index1,name ='index1'),
    path('2', views.index2,name ='index2'),
    path('email', views.mailing.as_view(),name ='mailing'),

]

Blog/send/models.py
from django.db import models

class Mail(models.Model):

    
    subject =models.CharField(blank =True,max_length =250)
    body =models.TextField(blank=True)
    from_email =models.EmailField()
    to_email =models.EmailField()
    sent_file =models.FileField(blank =True)

    def __str__(self):
        return self.subject

Blog/send/views.py
from django.shortcuts import render
from django.core.mail import send_mail,EmailMessage
from send.models import Mail
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView

def index1(request):
    send_mail('SUBJECT',
        'BODY',
        'klausmikelsonoriginal@gmail.com',
        ['1arshanahmad@gmail.com'],
        fail_silently=False)
    return render(request,'send/send.html')

def index2(request):
    SUBJECT =request.POST.get('subject')
    BODY =request.POST.get('body')
    from_email =request.POST.get('from_email')
    to_email =request.POST.get('to_email')
    sent_file =request.FILES.get('sent_file')

    email =EmailMessage(
        SUBJECT ,
        BODY ,
        from_email,
        [to_email] ,
        #attachments= sent_file,

    )

    email.attach_file(sent_file)
    email.send()
    return render(request,'send/send1.html')
        
class mailing(CreateView):        
    model =Mail
    fields =['subject','body','from_email','to_email','sent_file']
    template_name = 'send/send.html'



"""class index2(generic.ListView):
    model = ,Blogs1
    template_name ='blog/search.html'
    def get_queryset(self):
        query =self.request.GET.get('q') 
        object_list1 =Blogs.objects.filter(
            Q(author__username__icontains=query) )
        object_list2 =Blogs1.objects.filter(Q(blog_content__icontains=query))
        object_list =sorted(chain
        (object_list1,object_list2),
        key =lambda instance: instance.pk,reverse =True)
                
        return object_list
"""

Blog/send/templates/send/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ria</title>
    {%load staticfiles%}
    <link rel ="stylesheet" href ="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
    <link href ='https://fonts.googleapis.com/css?family=Satisfy' rel ='stylesheet' type ='text/css'>
    <link rel ="stylesheet" type ="text/css" href ="{%static 'blog/style.css' %}"/>
    <script src ="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src ="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.js"></script>
     
</head>
<body>
        <nav class ="navbar navbar-inverse"...>
                <div class ="container-fluid">
          
                    <div class ="navbar-header">
                        <button type ="button" class ="navbar-toggle" data-toggle="collapse" data-target="#topNavbar">
                          <span class="icon-bar" ></span>
                          <span class ="icon-bar" ></span>
                          <span class="icon-bar" ></span>
          
                       
                      </button>
          
                        <a class ="navbar-brand" href ="{%url 'blog:home' %}" >HOME</a>
                    </div>
          
                    <!--items-->
                    <div class ="collapse navbar-collapse" id ="topNavbar">
                        <ul class="nav navbar-nav">
                            <li class= "active">
                                <a href="{%url 'blog:home' %}">
                                  <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                                  Blogs
                                </a>
                            </li>
                            {%if user.is_authenticated%}
                            <li class= "">
                                  <a href="{%url 'blog:blog_content_add' %}">
                                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                                    Add Blogs
                                  </a>
                              </li>
                        </ul>
          
                        <form class ="navbar-form navbar-left" role ="search" method ="GET" action="{%url 'blog:search' %}">
                          <div class="form-group" >
                              <input type ="text" class ="form-control" name ="q" value ="{{request.GET.q}}" 
                              placeholder=" Search Posts">
                          </div> 
                          <button type ="submit" value="Search" class ="btn btn-default">Search</button>   
                        </form>
                          

                          
                        <ul class ="nav navbar-nav navbar-right">
                            {%if user.is_authenticated%}
                              <li class= "">
                                      <a href="{%url 'blog:blog_add'%}">
                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                        Personal Info
                                      </a>
                              </li>
                            {%endif%}    
          
                              <li class= "">
                                      <a href="{%url 'logout' %}">
                                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                                        Logout
                                      </a>
                                  </li>
                             {%else%}
                            <li class= "">
                                <a href="{%url 'login' %}">
                                  <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                                  LogIn
                                </a>
                            </li>
                            {%endif%} 
                        </ul>
                        
                    </div>
                </div>
            </nav>

            {%block body%}
            {%endblock%}
</body>
</html>

Blog/send/templates/send/form-template.html
{% for field in form %}
    <div class ="form-group">
        <div class ="col-sm-offset-2 col-sm-10">
            <span class ="text-danger small">{{ field.errors }}</span>



        </div>
        <label class ="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class ="col-sm-10">{{field}}</div>
    </div>
{%endfor%}    

Blog/send/templates/send/send.html
{%extends 'send/base.html' %}
{%block title %}Add a new blog {%endblock%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {%block body%}

<div class ="container-fluid">

    <div class ="row">

    <div class ="col-sm-12 col md-7">
        <div class ="panel panel-Subject:default">
            <div class ="panel-body">
                
                <form class ="form-horizontal" action ="{%url 'send:index2' %}" method ="POST" enctype ="multipart/form-data">
                    {% csrf_token %}
                    {% include 'send/form-template.html' %}
                    <div class ="form-group">
                        <div class ="col-sm-offset-2 col-sm-10">
                            <button type ="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>    
                </form>
            </div>
        </div>
    </div>
</div>    


{%endblock%}
</body>
</html>

Blog/send/templates/send/send1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Email</title>
</head>
<body>
    <h1>hello</h1>
</body>
</html>