Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('blog/',include('blog.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/v1/',include('blog.api_urls')),
    path('email/',include('send.urls'))


   # path('/<int:>/',include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root =settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

Blog/blog/urls.py
from django.urls import path 
from blog import views

app_name ='blog'
urlpatterns =[
    path('', views.homeview.as_view(),name ='home'),
    path('<int:pk>/', views.detailview.as_view(),name ='any_name'),
    path('blogs/add/',views.blogcreate.as_view(),name ='blog_add'),
    path('blogs1/add/',views.blog1create.as_view(),name ='blog_content_add'),
    #update_blog
    path('blogs/<int:pk>/',views.blogupdate.as_view(),name ='blog_update'),
    #delete
    path('blogs/<int:pk>/delete/',views.blogdelete.as_view(),name ='blog_delete'), 

    #registration
    path('register/',views.UserFormview.as_view(),name ='register'),
    #search
    path('search/',views.SearchResultView.as_view(),name ='search'),
    path('blogsview/', views.BlogsView.as_view(),name ='blogsview'),
    path('blogsview/<int:pk>/', views.Blogs1View.as_view(),name ='blogsview'),
     

    
]

Blog/send/urls.py
from django.urls import path 
from send import views

app_name ='send'
urlpatterns =[

    path('1', views.index1,name ='index1'),
    path('2', views.index2,name ='index2'),
    path('email', views.mailing.as_view(),name ='mailing'),

]

Blog/blog/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
#from django.conf import settings
#from django.utils.deprecation import RemovedInDjango30Warning


class Blogs(models.Model):

    author = models.OneToOneField(User,to_field='username',on_delete =models.CASCADE)
    blog_logo = models.FileField()
    created_at = models.DateTimeField(auto_now=True)
    edited_at = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse ('blog:any_name', kwargs ={'pk':self.pk})
    def __str__(self):

        return self.author.username
    
 
class Blogs1(models.Model):
    Author =models.ForeignKey(Blogs,on_delete =models.CASCADE,related_name='blog_detail')#bec of this
    # x only serializer linking is working
    blog_content = models.CharField(max_length =250)
    is_favorite =models.BooleanField(default =False)
    def __str__(self):
        return self.blog_content

Blog/blog/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password =forms.CharField(widget =forms.PasswordInput)

    class Meta:
        model =User 
        fields =['username','email' ,'password']

Blog/blog/views.py
from django.http import Http404
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.contrib import auth
from blog.models import Blogs, Blogs1
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.views.generic import View
from .forms import UserForm
from django.db.models import Q
from itertools import chain
from rest_framework import viewsets
from blog.serializers import bloggerserializer, blogger1serializer, blogger2serializer, blogger3serializer
from django.http import HttpResponse, JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status


class homeview(generic.ListView):
    template_name = 'blog/home.html'
    context_object_name = 'all_blogs'
    queryset = Blogs.objects.all()


class detailview(generic.DetailView):
    model = Blogs
    template_name = 'blog/details.html'


class blogcreate(CreateView):
    model = Blogs
    fields = ['author', 'blog_logo']
    template_name = 'blog/blogs.html'


class blog1create(CreateView):
    model = Blogs1
    fields = ['Author', 'blog_content']
    template_name = 'blog/blogs1.html'

    def get_success_url(self):
        return reverse('blog:home')


class blogupdate(UpdateView):
    model = Blogs
    field = ['author', 'blog_logo']


class blogdelete(DeleteView):
    model = Blogs
    success_url = reverse_lazy('blog:home')


class UserFormview(View):
    form_class = UserForm
    template_name = 'blog/registration_form.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # display full fill form
    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # cleaned (normalized ) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns user onjects if credential are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    auth.login(request, user)
                    return redirect('blog:home')
        return render(request, self.template_name, {'form': form})


class bloggerViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = bloggerserializer


class SearchResultView(generic.ListView):
    model = Blogs, Blogs1
    template_name = 'blog/search.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list1 = Blogs.objects.filter(
            Q(author__username__icontains=query))
        object_list2 = Blogs1.objects.filter(Q(blog_content__icontains=query))
        object_list = sorted(chain
                             (object_list1, object_list2),
                             key=lambda instance: instance.pk, reverse=True)

        return object_list


class BlogsView(APIView):
    def get(self, request):
        blogs = Blogs.objects.all()
        data = bloggerserializer(blogs, many=True).data
        return Response(data)

    def post(self, request):  # for adding blog_content
        # it doesnt matter wht id u provide it store data in id in which it want
        serializer = blogger1serializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class Blogs1View(APIView):  # detail

    def get_object(self, pk):
        try:
            return Blogs1.objects.filter(Author=pk)  # cant use get bec it only return single value
        except Blogs1.DoesNotExist:
            raise Http404

    def get_object1(self, pk):
        try:
            return Blogs1.objects.get(pk=pk)
        except Blogs1.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        snippet = self.get_object(pk)
        serializer = blogger2serializer(snippet, many=True).data  # many =true is neccessary if u
        # r sending multiple data
        return Response(serializer)

    def put(self, request, pk):
        snippet = self.get_object1(pk)
        serializer = blogger2serializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):  # give id of blog_content
        snippet = self.get_object1(pk)
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

Blog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ria</title>
    {%load static%}
    <link rel ="stylesheet" href ="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
    <link href ='https://fonts.googleapis.com/css?family=Satisfy' rel ='stylesheet' type ='text/css'>
    <link rel ="stylesheet" type ="text/css" href ="{%static 'blog/style.css' %}"/>
    <script src ="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src ="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.js"></script>
     
</head>
<body>
        <nav class ="navbar navbar-inverse"...>
                <div class ="container-fluid">
          
                    <div class ="navbar-header">
                        <button type ="button" class ="navbar-toggle" data-toggle="collapse" data-target="#topNavbar">
                          <span class="icon-bar" ></span>
                          <span class ="icon-bar" ></span>
                          <span class="icon-bar" ></span>
          
                       
                      </button>
          
                        <a class ="navbar-brand" href ="{%url 'blog:home' %}" >HOME</a>
                    </div>
          
                    <!--items-->
                    <div class ="collapse navbar-collapse" id ="topNavbar">
                        <ul class="nav navbar-nav">
                            <li class= "active">
                                <a href="{%url 'blog:home' %}">
                                  <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                                  Blogs
                                </a>
                            </li>
                            {%if user.is_authenticated%}
                            <li class= "">
                                  <a href="{%url 'blog:blog_content_add' %}">
                                    <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                                    Add Blogs
                                  </a>
                              </li>
                        </ul>
          
                        <form class ="navbar-form navbar-left" role ="search" method ="GET" action="{%url 'blog:search' %}">
                          <div class="form-group" >
                              <input type ="text" class ="form-control" name ="q" value ="{{request.GET.q}}" 
                              placeholder=" Search Posts">
                          </div> 
                          <button type ="submit" value="Search" class ="btn btn-default">Search</button>   
                        </form>
                          

                          
                        <ul class ="nav navbar-nav navbar-right">
                            {%if user.is_authenticated%}
                              <li class= "">
                                      <a href="{%url 'blog:blog_add'%}">
                                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                                        Personal Info
                                      </a>
                              </li>
                            {%endif%}    
          
                              <li class= "">
                                      <a href="{%url 'logout' %}">
                                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                                        Logout
                                      </a>
                                  </li>
                             {%else%}
                            <li class= "">
                                <a href="{%url 'login' %}">
                                  <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                                  LogIn
                                </a>
                            </li>
                            {%endif%} 
                        </ul>
                        
                    </div>
                </div>
            </nav>

            {%block body%}
            {%endblock%}
</body>
</html>

Blog/blog/templates/blog/blogs.html
{%extends 'blog/base.html' %}
{%block title %}Add a new blog {%endblock%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {%block body%}

<div class ="container-fluid">

    <div class ="row">

    <div class ="col-sm-12 col md-7">
        <div class ="panel panel-default">
            <div class ="panel-body">
                
                <form class ="form-horizontal" action ="" method ="POST" enctype ="multipart/form-data">
                    {% csrf_token %}
                    {% include 'blog/form-template.html' %}
                    <div class ="form-group">
                        <div class ="col-sm-offset-2 col-sm-10">
                            <button type ="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>    
                </form>
            </div>
        </div>
    </div>
</div>    

<a href="{%url 'password_change'%}" class="btn btn-primary btn-sm" role="button">Change Password</a>
</a>

<a href="{%url 'send:mailing'%}" class="btn btn-primary btn-sm" role="button">Send Email</a>
</a>

{%endblock%}
</body>
</html>

Blog/blog/templates/blog/blogs1.html
{%extends 'blog/base.html' %}
{%block title %}Add a new blog {%endblock%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {%block body%}

<div class ="container-fluid">

    <div class ="row">

    <div class ="col-sm-12 col md-7">
        <div class ="panel panel-default">
            <div class ="panel-body">
                
                <form class ="form-horizontal" action ="" method ="post" enctype ="multipart/form-data">
                    {% csrf_token %}
                    {% include 'blog/form-template.html' %}
                    <div class ="form-group">
                        <div class ="col-sm-offset-2 col-sm-10">
                            <button type ="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>    
                </form>
            </div>
        </div>
    </div>
</div>    

{%endblock%}
</body>
</html>

Blog/blog/templates/blog/details.html
{% extends 'blog/base.html' %}
{%block body%}

<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
</head>
<body><p></p>
  
            <h1>{{object.author}}:</h1>   

      <ol>{%for x in object.blogs1_set.all%}
        <li>{{x.blog_content}}asdf  </li>
                
                {%endfor%}
         
        </ol>
      
        {% endblock %}    
     
</body>
</html>

Blog/blog/templates/blog/form-template.html
{% for field in form %}
    <div class ="form-group">
        <div class ="col-sm-offset-2 col-sm-10">
            <span class ="text-danger small">{{ field.errors }}</span>



        </div>
        <label class ="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class ="col-sm-10">{{field}}</div>
    </div>
{%endfor%}    

Blog/blog/templates/blog/home.html
{% extends 'blog/base.html' %}


{% block body %}
  
<div class="albums-container container-fluid">
    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Welcome{%if user.is_authenticated%} {{ user.username }}{%else%} Guest{%endif%}</h3>
        </div>

        {% if all_blogs %}
        
            {% for x in all_blogs %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="/blog/{{x.id}}/">
                            <img src="{{ x.blog_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ x.author }}</h2>
                            

                            <!-- View Details -->
                            <a href="/blog/{{x.id}}/" class="btn btn-primary btn-sm" role="button">View Details</a>
                            {%if user.is_authenticated%}
                            <!-- Delete Album -->
                            <form action="{% url 'blog:blog_delete' x.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="pk" value="{{ x.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                            {%endif%}
                            <!-- Favorite Album -->
                            <a href="{% url 'blog:any_name' x.id %}" class="btn btn-default btn-sm btn-favorite" role="button"></a>
                                <span class="glyphicon glyphicon-star {% if album.is_favorite %}active{% endif %}"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'blog:blog_add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Blog
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- If user searches and there are songs -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>{{ song.album.artist }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}

Blog/blog/templates/blog/registration_form.html
{%extends 'blog/base.html' %}
{%block title %}Registration {%endblock%}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {%block body%}

<div class ="container-fluid">

    <div class ="row">

    <div class ="col-sm-12 col md-7">
        <div class ="panel panel-default">
            <div class ="panel-body">
                    <h2>Create a new account</h2>
                <form class ="form-horizontal" action ="" method ="post" enctype ="multipart/form-data">
                    {% csrf_token %}
                    {% include 'blog/form-template.html' %}
                    <div class ="form-group">
                        <div class ="col-sm-offset-2 col-sm-10">
                            <button type ="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>    
                </form>
            </div>
        </div>
    </div>
</div>    

{%endblock%}
</body>
</html>

Blog/blog/templates/blog/search.html
{%extends 'blog/base.html' %}

{%block body%}
<h1>search results</h1>

<ul>
    {% for x in object_list  %} 
      <li>
      {{x}}{% if x.author.username %}(blogger username){%else%}(blog in {{x.Author.author.username}}'s blog){%endif%} 
              
      </li>
    {% endfor %}
  </ul>

  <ul>
    {% for x in object_list2  %} 
      <li>
        {{blogs }}
      </li>
    {% endfor %}
  </ul>





  {%endblock%}